version: '3.9'

services:
  restaurant-postgressql-database:
    image: postgres:16.2
    env_file: .env
    container_name: restaurant-postgressql-database
    ports:
      - "2000:5432"
    networks:
      - app-network
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_DATABASE}

  restaurant-backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: restaurant-backend-app
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - restaurant-postgressql-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRESDB_ADDRESS}/${POSTGRESDB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRESDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRESDB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  app-network:
    external: true
