version: '3.9'

services:
  restaurant-postgressql-database:
    image: dmytrotelprofitsoft.azurecr.io/restaurant-postgresql:16.2
    env_file: .env
    container_name: restaurant-postgressql-database
    ports:
      - "2000:5432"
    networks:
      - app-network
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dmytro
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: restaurant_db

  restaurant-backend-app:
    image: dmytrotelprofitsoft.azurecr.io/restaurant-backend-app:latest
    container_name: restaurant-backend-app
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - restaurant-postgressql-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant-postgressql-database:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: dmytro
      SPRING_DATASOURCE_PASSWORD: qwerty1234
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  app-network:
    external: true

