name: CI/CD for Dish service

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        run: |
          docker login <ACR_LOGIN_SERVER> -u <ACR_USERNAME> -p <ACR_PASSWORD>

      - name: Build and push PostgreSQL image
        run: |
          docker pull postgres:16.2
          docker tag postgres:16.2 dmytrotelprofitsoft.azurecr.io/restaurant-postgresql:16.2 
          docker push dmytrotelprofitsoft.azurecr.io/restaurant-postgresql:16.2  

      - name: Build and push backend app image
        run: |
          docker build -t dmytrotelprofitsoft.azurecr.io/restaurant-backend-app:latest -f Dockerfile .
          docker push dmytrotelprofitsoft.azurecr.io/restaurant-backend-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          # Ensure the docker-compose.prod.yml file is present
          ls -l
          cat docker-compose.prod.yml
          # Deploy to Azure Web App
          az webapp config container set --name dmtelprofitsortdishservice --resource-group dm-profitsoft-group --multicontainer-config-type compose --multicontainer-config-file docker-compose.prod.yml
