name: CI/CD for Dish service

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: dmytrotelprofitsoft.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push PostgreSQL image
        run: |
          docker pull postgres:16.2
          docker tag postgres:16.2 myregistry.azurecr.io/restaurant-postgresql:16.2  # Replace with your ACR login server
          docker push myregistry.azurecr.io/restaurant-postgresql:16.2  # Replace with your ACR login server

      - name: Build and push backend app image
        run: |
          docker build -t myregistry.azurecr.io/restaurant-backend-app:latest -f Dockerfile .  # Replace with your ACR login server
          docker push myregistry.azurecr.io/restaurant-backend-app:latest  # Replace with your ACR login server

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dmtelprofitsortdishservice
          slot-name: production
          images: |
            myregistry.azurecr.io/restaurant-backend-app:latest  # Replace with your ACR login server
            myregistry.azurecr.io/restaurant-postgresql:16.2  # Replace with your ACR login server
